stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet format services/osrs-guide/src/OsrsGuide.Web/OsrsGuide.Web.csproj --verify-no-changes
    - dotnet format services/monitor/src/Monitor.Web/Monitor.Web.csproj --verify-no-changes

build-osrs-guide:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f services/osrs-guide/Dockerfile -t $CI_REGISTRY_IMAGE/osrs-guide:latest .
    - docker push $CI_REGISTRY_IMAGE/osrs-guide:latest

build-monitor:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f services/monitor/Dockerfile -t $CI_REGISTRY_IMAGE/monitor:latest .
    - docker push $CI_REGISTRY_IMAGE/monitor:latest

deploy-osrs-guide:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - 'curl -L https://fly.io/install.sh | sh'
    - export FLY_API_TOKEN=$FLY_API_TOKEN
    - /root/.fly/bin/flyctl deploy -c infra/fly/osrs-guide.fly.toml
  when: manual

deploy-monitor:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - 'curl -L https://fly.io/install.sh | sh'
    - export FLY_API_TOKEN=$FLY_API_TOKEN
    - /root/.fly/bin/flyctl deploy -c infra/fly/monitor.fly.toml
  when: manual
